version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: phoenix_symfony_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LC_COLLATE: pl_PL.UTF-8
      LC_CTYPE: pl_PL.UTF-8
      POSTGRES_INITDB_ARGS: "--locale=pl_PL.UTF-8 --encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  phoenix:
    build:
      context: ./phoenix-api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ecto://postgres:postgres@postgres/phoenix_symfony_dev
      SECRET_KEY_BASE: "your-secret-key-base-here-change-in-production"
      PHX_HOST: localhost
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./phoenix-api:/app
      - phoenix_deps:/app/deps
      - phoenix_build:/app/_build
    command: mix phx.server

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  symfony:
    build:
      context: ./symfony-admin
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/phoenix_symfony_dev
      PHOENIX_API_URL: http://phoenix:4000/api
      REDIS_URL: redis://redis:6379
      APP_ENV: dev
      APP_SECRET: "your-app-secret-here-change-in-production"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - phoenix
      - redis
    volumes:
      - ./symfony-admin:/var/www
      - symfony_vendor:/var/www/vendor
      - symfony_var:/var/www/var
    command: php -S 0.0.0.0:8080 -t public

volumes:
  postgres_data:
  redis_data:
  phoenix_deps:
  phoenix_build:
  symfony_vendor:
  symfony_var:

networks:
  default:
    name: phoenix-symfony-network