framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: phoenix_symfony_admin

        # Redis configuration for production-ready caching
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        # Dedicated pools for different cache types
        pools:
            phoenix_api_cache:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 300 # 5 minutes TTL for API responses
